# Generated by Django 3.2.8 on 2021-10-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_boughtitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Processed by seller'), (2, 'In Shipping'), (3, 'Made It')], default=1),
        ),
    ]
