# Generated by Django 3.2.8 on 2021-10-12 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_boughtitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtitem',
            name='date_bought',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='boughtitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Processed By Seller'), (2, 'In Shipping'), (3, 'Made It')], default=1),
        ),
    ]
